### ISSUE TITLE
Can't react-native start

### ISSUE THREAD

**Issue by fedwatch** [fangwei716/ThirtyDaysOfReactNative#68]
module.js:540
    throw err;
    ^

Error: Cannot find module 'invariant'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (K:/rnDemos/30-days-of-react-native-development/node_modules/_react-native@0.40.0@react-native/packager/react-packager/src/lib/GlobalTransformCache.js:16:19)
    at Module._compile (module.js:643:30)
    at loader (K:\rnDemos\30-days-of-react-native-development\node_modules\_babel-register@6.26.0@babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (K:\rnDemos\30-days-of-react-native-development\node_modules\_babel-register@6.26.0@babel-register\lib\node.js:154:7)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)

**Comment by khaitq7** [comment]
Please ask me . I have look at the same issue .
